"""Create initial users, events, and metrics models

Revision ID: 2751190d4875
Revises:
Create Date: 2026-02-25 13:53:03.604921

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2751190d4875"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # User Table
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("authentik_sub", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("github_username", sa.String(), nullable=True),
        sa.Column("github_access_token", sa.String(), nullable=True),
        sa.Column("github_token_expiry", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_github_sync", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_username"),
    )
    op.create_index(
        op.f("ix_user_authentik_sub"), "user", ["authentik_sub"], unique=True
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)

    # Daily Stats table
    op.create_table(
        "daily_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("commit_count", sa.Integer(), nullable=False),
        sa.Column("pr_opened_count", sa.Integer(), nullable=False),
        sa.Column("pr_merged_count", sa.Integer(), nullable=False),
        sa.Column("pr_reviewed_count", sa.Integer(), nullable=False),
        sa.Column("issues_opened_count", sa.Integer(), nullable=False),
        sa.Column("lines_added_count", sa.Integer(), nullable=False),
        sa.Column("lines_deleted_count", sa.Integer(), nullable=False),
        sa.Column("repos_contributed_to_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_user_date"),
    )
    op.create_index(op.f("ix_daily_stats_date"), "daily_stats", ["date"], unique=False)
    op.create_index(op.f("ix_daily_stats_id"), "daily_stats", ["id"], unique=False)
    op.create_index(
        op.f("ix_daily_stats_user_id"), "daily_stats", ["user_id"], unique=False
    )

    # Event table
    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("GITHUB", "GITLAB", "BITBUCKET", name="eventsource"),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum("COMMIT", "PULL_REQUEST", "ISSUE", "COMMENT", name="eventtype"),
            nullable=False,
        ),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("github_event_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_github_event_id"), "event", ["github_event_id"], unique=True
    )
    op.create_index(
        op.f("ix_event_occurred_at"), "event", ["occurred_at"], unique=False
    )
    op.create_index(op.f("ix_event_user_id"), "event", ["user_id"], unique=False)

    # PR Analytics table
    op.create_table(
        "pr_analytics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("github_pr_id", sa.Integer(), nullable=False),
        sa.Column("repo_name", sa.String(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("DRAFT", "OPEN", "CLOSED", "MERGED", name="prstate"),
            nullable=False,
        ),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("comment_count", sa.Integer(), nullable=False),
        sa.Column("files_changed", sa.Integer(), nullable=False),
        sa.Column("lines_added", sa.Integer(), nullable=False),
        sa.Column("lines_deleted", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_pr_id"),
    )
    op.create_index(
        op.f("ix_pr_analytics_user_id"), "pr_analytics", ["user_id"], unique=False
    )

    # Weekly Languages table
    op.create_table(
        "weekly_languages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("week_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lines_written", sa.Integer(), nullable=False),
        sa.Column("repo_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "language", "week_start", name="uq_user_language_week_start"
        ),
    )
    op.create_index(
        op.f("ix_weekly_languages_user_id"),
        "weekly_languages",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weekly_languages_user_id"), table_name="weekly_languages")
    op.drop_table("weekly_languages")

    op.drop_index(op.f("ix_pr_analytics_user_id"), table_name="pr_analytics")
    op.drop_table("pr_analytics")

    op.drop_index(op.f("ix_event_user_id"), table_name="event")
    op.drop_index(op.f("ix_event_occurred_at"), table_name="event")
    op.drop_index(op.f("ix_event_github_event_id"), table_name="event")
    op.drop_table("event")

    op.drop_index(op.f("ix_daily_stats_user_id"), table_name="daily_stats")
    op.drop_index(op.f("ix_daily_stats_id"), table_name="daily_stats")
    op.drop_index(op.f("ix_daily_stats_date"), table_name="daily_stats")
    op.drop_table("daily_stats")

    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_user_authentik_sub"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
